codec/src/codec.rs
spdmlib/src/msgs/spdm_codec.rs

Rather than making the struct field `pub`, we create a `new` function so that
we can assert that the u32 value can fit in fewer than 32 bits. Since the
struct field is no longer public, a `get` function has been added to retrieve
the internal value.

Improve the safety of u24

---

spdmlib/src/common/mod.rs
spdmlib/src/requester/challenge_req.rs
spdmlib/src/requester/context.rs
spdmlib/src/requester/end_session_req.rs
spdmlib/src/requester/finish_req.rs
spdmlib/src/requester/get_capabilities_req.rs
spdmlib/src/requester/get_certificate_req.rs
spdmlib/src/requester/get_digests_req.rs
spdmlib/src/requester/get_measurements_req.rs
spdmlib/src/requester/get_version_req.rs
spdmlib/src/requester/heartbeat_req.rs
spdmlib/src/requester/key_exchange_req.rs
spdmlib/src/requester/key_update_req.rs
spdmlib/src/requester/negotiate_algorithms_req.rs
spdmlib/src/requester/psk_exchange_req.rs
spdmlib/src/requester/psk_finish_req.rs
spdmlib/src/requester/respond_if_ready_req.rs
spdmlib/src/requester/vendor_req.rs
spdmlib/src/responder/context.rs
spdmlib/src/testlib.rs
spdmlib/tests/common/fake_device_io.rs
test/spdm-emu/src/socket_io_transport.rs
test/spdm-emu/src/spdm_emu.rs
test/spdm-emu/src/tcp_transport.rs
test/spdm-requester-emu/src/main.rs
test/spdm-responder-emu/src/main.rs

fix #204 
Add timeout to receive according SPDM spec to solve issue #204.
Notably, RTT is *NOT* calculated in timeout. When provisioning,
RTT need to be taken into account.
Signed-off-by: Longlong Yang [longlong.yang@intel.com](mailto:longlong.yang@intel.com)

Timeout: need implement the timeout according to SPDM spec.

---

spdmlib/src/common/mod.rs
spdmlib/src/crypto/spdm_ring/asym_verify_impl.rs
spdmlib/src/requester/get_capabilities_req.rs
spdmlib/src/requester/get_measurements_req.rs
spdmlib/src/requester/get_version_req.rs
spdmlib/src/requester/key_exchange_req.rs
spdmlib/src/requester/negotiate_algorithms_req.rs
spdmlib/src/requester/psk_exchange_req.rs

fix #199 
As per specification of SPDM1.2, change transcript calculation to support
1. SPDMsign(PrivKey, transcript, "key_exchange_rsp signing");
2. SPDMsignatureVerify(PubKey,signature, transcript, "key_exchange_rsp signing");

Spdm1.2 transcript: Add support to Spdm1.2 key_exchange_rsp signing

---

spdmlib/src/common/mod.rs
spdmlib/src/message/key_exchange.rs
spdmlib/src/message/measurement.rs
spdmlib/src/message/mod.rs
spdmlib/src/requester/key_exchange_req.rs
spdmlib/src/responder/key_exchange_rsp.rs
spdmlib/src/responder/measurement_rsp.rs

fix #231 and #232
Add the missing parts of Spdm1.2 new features MEASUREMENTS response param2
ContentChange and KEY_EXCHANGE request SessionPolicy.

Spdm1.2: Add support to SessionPolicy and ContentChange

---

spdmlib/src/common/mod.rs
spdmlib/src/message/measurement.rs
spdmlib/src/message/mod.rs
spdmlib/src/requester/get_measurements_req.rs
spdmlib/src/responder/measurement_rsp.rs
test/spdm-requester-emu/src/main.rs

1. add RAW_BIT_STREAM_REQUESTED to SpdmMeasurementeAttributes
2. as per SPDM spec., change INCLUDE_SIGNATURE in SpdmMeasurementeAttributes
to SIGNATURE_REQUESTED
3. send_receive_spdm_measurement api signature is changed to be able to pass
spdm_measuremente_attributes and get total_number as output
4. get_measurements request to set content changed in runtime info.

measurement: add RawBitStreamRequested support to SpdmMeasurementeAttributes

---

mctp_transport/src/header.rs
spdmlib/build.rs
spdmlib/etc/config.json
spdmlib/src/common/mod.rs
spdmlib/src/common/session.rs
spdmlib/src/requester/context.rs
spdmlib/src/requester/get_capabilities_req.rs
spdmlib/src/responder/capability_rsp.rs
spdmlib/src/responder/context.rs
spdmlib/tests/common/utils.rs
test/spdm-emu/src/socket_io_transport.rs
test/spdm-emu/src/spdm_emu.rs
test/spdm-requester-emu/src/main.rs
test/spdm-responder-emu/src/main.rs

1. add data_transfer_size and max_spdm_msg_size to SpdmConfigInfo
2. add req_data_transfer_size_sel req_max_spdm_msg_size_sel: u32
and rsp_data_transfer_size_sel rsp_max_spdm_msg_size_sel: u32
to SpdmNegotiateInfo

Common: add data_transfer_size and max_spdm_msg_size to SpdmConfigInfo

---

spdmlib/build.rs
spdmlib/etc/config.json
spdmlib/src/common/mod.rs
spdmlib/src/common/session.rs
spdmlib/src/requester/key_exchange_req.rs
spdmlib/src/responder/key_exchange_rsp.rs

1. add heartbeat_period to SpdmSession to let requester to record
the heartbeat_period chose by responder.

key_exchange: add heartbeat_period to SpdmSession

---

spdmlib/build.rs
spdmlib/etc/config.json
spdmlib/src/common/key_schedule.rs
spdmlib/src/common/mod.rs
spdmlib/src/common/opaque.rs
spdmlib/src/common/session.rs
spdmlib/src/requester/finish_req.rs
spdmlib/src/requester/key_exchange_req.rs
spdmlib/src/requester/key_update_req.rs
spdmlib/src/requester/negotiate_algorithms_req.rs
spdmlib/src/requester/psk_exchange_req.rs
spdmlib/src/requester/psk_finish_req.rs
spdmlib/src/responder/finish_rsp.rs
spdmlib/src/responder/key_exchange_rsp.rs
spdmlib/src/responder/key_update_rsp.rs
spdmlib/src/responder/psk_exchange_rsp.rs
spdmlib/src/responder/psk_finish_rsp.rs
spdmlib/tests/common/utils.rs
test/spdm-responder-emu/src/main.rs

1. added secure_spdm_version to SpdmSession.
2. implemented Secured Messages using SPDM Specification in Opaque.rs

secure_spdm_version: add secure_spdm_version support.

---

spdmlib/src/requester/get_measurements_req.rs
test/spdm-requester-emu/src/main.rs

1. add spdm_measurement_record_structure from measurements response as
output parameter to send_receive_spdm_measurement_record.

get_measurements_req: expose spdm_measurement_record_structure outside

---

spdmlib/src/message/vendor.rs
spdmlib/src/requester/vendor_req.rs
spdmlib/src/responder/vendor_rsp.rs

1. rename ReqPayloadStruct to VendorDefinedReqPayloadStruct and
rename ResPayloadStructto VendorDefinedRspPayloadStruct
for better readability

vendor_defined: rename ReqPayloadStruct and ResPayloadStruct

---

spdmlib/src/common/mod.rs
spdmlib/src/requester/challenge_req.rs
spdmlib/src/requester/context.rs
spdmlib/src/requester/finish_req.rs
spdmlib/src/requester/get_certificate_req.rs
spdmlib/src/requester/get_measurements_req.rs
spdmlib/src/requester/key_exchange_req.rs
spdmlib/src/requester/psk_exchange_req.rs
spdmlib/src/requester/psk_finish_req.rs
test/spdm-requester-emu/src/main.rs

1. change peer_cert_chain in struct SpdmPeerInfo to hold
[Option\<SpdmCertChain\>; 8] instread of SpdmCertChain

peer_info: support multiple peer certificate chains

---

fuzz-target/pass_context/src/pass_responder.rs
fuzz-target/responder/certificate_rsp/src/main.rs
fuzz-target/responder/digest_rsp/src/main.rs
fuzz-target/responder/end_session_rsp/src/main.rs
spdmlib/src/responder/certificate_rsp.rs
spdmlib/src/responder/context.rs
spdmlib/src/responder/digest_rsp.rs
spdmlib/src/responder/end_session_rsp.rs
test/spdm-emu/src/secret_impl_sample.rs
test/spdm-responder-emu/src/main.rs

These patches fix a communication issue between the rust-spdm of spdm-responder-emu and the libspdm version of spdm_requester_emu #276. Fixed #277, #279, #280
**Note:** https://github.com/jyao1/rust-spdm/issues/278 issue is not resolved.This requires the libspdm's spdm_requester_emu to remove the do_app_session_via_spdm related code.

Fix issues related to #276

---

spdmlib/src/common/session.rs

SPDM spec 1.2 Key schedule section says:
HKDF-Expand ( Master-Secret, bin_str8, Hash.Length ) = Export Master Secret.
This patch fix #290.
Signed-off-by: xiaoyuxlu <xiaoyu1.lu@intel.com>

ExportMasterSecret should derive from MasterSecret

---

.github/workflows/coverage.yml

e.g. If we need to release version v0.1.0,
we create v0.1.0/alpha tag first. The coverage will be run. Then we need to check that the coverage will not decrease.

CI/CD: run coverage when every tag created.

---

spdmlib/src/message/algorithm.rs
spdmlib/src/message/mod.rs

REF: #320 
When config info is the default, the following checkpoint should fail. But these checkpoints were successful.
```
assert_eq!(
payload.measurement_specification_sel,
SpdmMeasurementSpecification::DMTF
);
assert_eq!(
payload.measurement_hash_algo,
SpdmMeasurementHashAlgo::RAW_BIT_STREAM
);
assert_eq!(payload.base_asym_sel, SpdmBaseAsymAlgo::TPM_ALG_RSASSA_2048);
assert_eq!(payload.base_hash_sel, SpdmBaseHashAlgo::TPM_ALG_SHA_256);
```
Fix these checkpoints by adding corresponding config.

Test: Fix algorithm test issue.

---

.github/workflows/fuzz.yml

rust version for rust-spdm is specific.
cargo install --force afl will always install a latest version of AFL. It may cause problem. Eg:
AFL LLVM runtime is not built with Rust rustc-1.65.0-nightly-d394408, run `cargo install --force afl` to build it.

CI/CD: Force install the specific version of afl

---

spdmlib/src/protocol/capability.rs
spdmlib/src/responder/measurement_rsp.rs

1. requester from rust-spdm <-> responder from spdm-emu
2. responder from rust-spdm <-> requester from spdm-emu
3. requester from rust-spdm <-> responder from rust-spdm
Signed-off-by: Yang Longlong <longlong.yang@intel.com>

pass cross-testing with spdm-emu v2.2.0 using hash update.

---

fuzz-target/fuzzlib/Cargo.toml
fuzz-target/requester/algorithm_req/Cargo.toml
fuzz-target/requester/capability_req/Cargo.toml
fuzz-target/requester/certificate_req/Cargo.toml
fuzz-target/requester/challenge_req/Cargo.toml
fuzz-target/requester/digest_req/Cargo.toml
fuzz-target/requester/end_session_req/Cargo.toml
fuzz-target/requester/finish_req/Cargo.toml
fuzz-target/requester/heartbeat_req/Cargo.toml
fuzz-target/requester/key_exchange_req/Cargo.toml
fuzz-target/requester/key_update_req/Cargo.toml
fuzz-target/requester/measurement_req/Cargo.toml
fuzz-target/requester/psk_exchange_req/Cargo.toml
fuzz-target/requester/psk_finish_req/Cargo.toml
fuzz-target/requester/version_req/Cargo.toml
fuzz-target/responder/algorithm_rsp/Cargo.toml
fuzz-target/responder/capability_rsp/Cargo.toml
fuzz-target/responder/certificate_rsp/Cargo.toml
fuzz-target/responder/challenge_rsp/Cargo.toml
fuzz-target/responder/digest_rsp/Cargo.toml
fuzz-target/responder/end_session_rsp/Cargo.toml
fuzz-target/responder/finish_rsp/Cargo.toml
fuzz-target/responder/heartbeat_rsp/Cargo.toml
fuzz-target/responder/key_update_rsp/Cargo.toml
fuzz-target/responder/keyexchange_rsp/Cargo.toml
fuzz-target/responder/measurement_rsp/Cargo.toml
fuzz-target/responder/psk_finish_rsp/Cargo.toml
fuzz-target/responder/pskexchange_rsp/Cargo.toml
fuzz-target/responder/version_rsp/Cargo.toml

Fix CI error:
error: failed to run custom build command for `afl v0.12.14`
Error: failed to run custom build command for `afl v0.12.14`
Caused by:
process didn't exit successfully: `/home/runner/work/rust-spdm/rust-spdm/target/debug/build/afl-7c10dbd9de693d33/build-script-build` (signal: 4, SIGILL: illegal instruction)

Fuzzing: Fix AFL version problem.

---

Cargo.toml
sh_script/build.sh

ISSUE: https://github.com/jyao1/rust-spdm/issues/396
tdisp has conflicts with the updates by issue#380 (remove mutable refs from SpdmContext). Further more, tdisp itself needs other refactors. So it is temporarily removed from Cargo.toml and build.sh. A new issue will be created to track it is added back.

Remove tdisp from rust-spdm

---

sh_script/build.sh
spdmlib/src/requester/key_exchange_req.rs
spdmlib/src/requester/psk_exchange_req.rs
spdmlib/src/responder/key_exchange_rsp.rs
spdmlib/src/responder/psk_exchange_rsp.rs

Relevant: https://github.com/DMTF/libspdm/issues/1424

correct the session id creation.

---

spdmlib/src/requester/vendor_req.rs
spdmlib/src/responder/vendor_rsp.rs

vendor defined request/response should not be treated as app message.

---

spdmlib/src/message/error.rs

Fix https://github.com/jyao1/rust-spdm/issues/499

remove SpdmErrorInvalidSession because it is deprecated.

---

spdmlib/src/common/mod.rs
spdmlib/src/requester/get_certificate_req.rs

It is to avoid invalid cert chain impact.
Fix: https://github.com/jyao1/rust-spdm/issues/444

add peer_cert_chain_temp to process the get_cert.

---

spdmlib/src/responder/context.rs

Fix #562
The input data of dispatch_secured_app_message shall be spdm_buffer[0..decode_size], not receive_buffer[0..used].
spdm_buffer contains the decrypted data, while receive_buffer contains the raw SPDM message, including the encrypted data.

spdmlib/responder: Fix error when call dispatch_secured_app_message

---

spdmlib/src/responder/mod.rs

Fix #561
app_message_handler shall be declared as public otherwise it cannot be used outside of rust-spdm.

Update mod app_message_handler to pub

---

spdmlib/src/responder/version_rsp.rs

Fix #560
According to DSP0274 1.2 Section 10.2:
"After receiving a valid GET_VERSION request, the Responder shall invalidate state and data associated with all previous requests from the same Requester. All active sessions between the Requester and the Responder are terminated and information (such as session keys, session IDs) for those sessions should not be used anymore. Additionally, this message shall clear the previously Negotiated State, if any, in both the Requester and its corresponding Responder."

Reset context instead of runtime_info when GET_VERSION

---

spdmlib/src/responder/app_message_handler.rs
spdmlib/src/responder/context.rs

Fix #563
The returned value of dispatch_secured_app_message_cb is not correct. It should return the size as well.

Change return result of dispatch_secured_app_message_cb

---

spdmlib_crypto_mbedtls/Cargo.toml
spdmlib_crypto_mbedtls/src/dhe_impl.rs

Fix: #595
The C interface should not use SpdmDheExchangeStruct to store exchange key. Output size from mbedtls may larger than the max size of SpdmDheExchangeStruct.
Fix: #558 
Zero keys.

Fix wrong implmentation of DHE.

---

fuzz-target/fuzzlib/src/secret.rs
spdmlib/src/secret/mod.rs
spdmlib/src/secret/secret_callback.rs
test/spdm-emu/src/secret_impl_sample.rs

SpdmRequesterDataSignCbType and SpdmResponderDataSignCbType are identical and these function definition voilates the sigle responsibilty principle. To implement them need to look for SPDM spec. for example: op_code parameter. This will increase the difficulty to implement the interface
Current spdmlib have already use the SpdmAsymSign interface for signing. The SpdmAsymSign only takes two parameter to determine the private key. Then the implementation for SpdmAsymSign is only need to use (secret_key, data) for sign operation.
Note: There are restrictions to seek secret key. Fix this is not in the current scope.

Remove unused secret callback, Ref: #624

---

fuzz-target/fuzzlib/src/secret.rs
fuzz-target/requester/measurement_req/src/main.rs
fuzz-target/responder/measurement_rsp/src/main.rs
spdmlib/src/responder/measurement_rsp.rs
spdmlib/src/secret/mod.rs
spdmlib/src/secret/secret_callback.rs
spdmlib/src/testlib.rs
spdmlib/tests/common/crypto_callbacks.rs
spdmlib/tests/common/testlib.rs
spdmlib_crypto_mbedtls/tests/common/crypto_callbacks.rs
test/spdm-emu/src/crypto_callback.rs
test/spdm-emu/src/secret_impl_sample.rs
test/spdm-responder-emu/src/main.rs

Fix #644 
SpmdSecret -> SpdmSecretMeasurement, SpdmSecretPsk
Usage:
```
SpdmSecretMeasurement
spdmlib::secret::measurement::register
spdmlib:secret::messurement::measurement_collection
spdmlib:secret::messurement::generate_measurement_summary_hash
SpdmSecretPsk
spdmlib::secret::psk::register
spdmlib::secret::psk::handshake_secret_hkdf_expand
spdmlib::secret::psk::master_secret_hkdf_expand
SpdmSecretAsymSign
spdmlib:secret::asym_sign::register
spdmlib:secret::asym_sign::sign
```

Split SpdmSecret to SpdmSecretPsk and SpdmSecretMeasurement

---

spdmlib/src/responder/vendor_rsp.rs

vendor_defined_request_payload need to be checked before unwrap. 
I am working on vendor fuzz tests, and this issue need to be fixed

Check vendor_defined_request_payload

---

spdmlib/etc/config.json

max_cert_chain_data_size:
3500: cargo run -p spdm-responder-emu --no-default-features --features "spdm-ring"
4096: cargo run -p spdm-responder-emu --no-default-features --features "spdm-ring,hashed-transcript-data"

update cfg to avoid runtime stack too large.

---

fuzz-target/requester/key_update_req/src/main.rs
fuzz-target/responder/certificate_rsp/src/main.rs

The provision of `negotiate_info.base_hash_sel` is missing in certificate_rsp fuzz test.  
Add it to pass `append_message_b()`
https://github.com/jyao1/rust-spdm/blob/f4ad2effb00a81c4c130b0a80dcb11b4b3a10716/spdmlib/src/responder/certificate_rsp.rs#L67-L79

Fuzz: add missing base_hash_sel

---

spdmlib/src/requester/psk_finish_req.rs

After `handle_spdm_psk_finish_response`, `get_session_via_id` is possible to be none. So we need check none value again before unwarp it.
This is the same issue with #627 but appeared in another place.

Check none session after handle_spdm_psk_finish_response

---

.github/workflows/coverage.yml

llvm-tools-preview is missing.
This patch add llvm-tools-preview component
Fix: #693

[CI/CD] update coverage.yml

---

spdmlib/src/message/vendor.rs

currently, the constant MAX_SPDM_VENDOR_DEFINED_PAYLOAD_SIZE is only visible to spdmlib crate. It should be public to outside of spdmlib crate, because the caller outside of spdmlib may need to create VendorDefinedRspPayloadStruct or VendorDefinedReqPayloadStruct, which contains an array vendor_defined_rsp_payload. And its size should be MAX_SPDM_VENDOR_DEFINED_PAYLOAD_SIZE.

make MAX_SPDM_VENDOR_DEFINED_PAYLOAD_SIZE public to outside of crate.
