jyao1/rust-spdm

spdmlib/Cargo.toml, spdmlib/tests/common/crypto_callbacks.rs, spdmlib/tests/common/fake_device_io.rs, spdmlib/tests/common/mod.rs, spdmlib/tests/common/shared_buffer.rs, spdmlib/tests/common/utils.rs, spdmlib/tests/test_client_server.rs
TBD: need add more different algorithm combinations
=> spdmlib: Add test_client_server integration test

spdmlib/src/crypto/spdm_ring/cert_operation_impl.rs
Signed-off-by: Xiaoyu Lu <xiaoyux.lu@intel.com>
=> update ring to 0.16.20 and webpki to 0.22.0

fuzz-target/random_requester/src/main.rs, fuzz-target/requester/measurement_req/src/main.rs, spdmlib/src/common.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/responder/measurement_rsp.rs, spdmlib/src/session.rs, test/spdm-requester-emu/src/main.rs
=> session based measurement should use session based M cache

spdmlib/src/crypto/mod.rs
=> fix #211 cargo test may fail at test_case0_aead_register

spdmlib/src/crypto/mod.rs, spdmlib/src/message/vendor.rs, spdmlib/src/requester/mod.rs, spdmlib/src/requester/vendor_req.rs, spdmlib/src/responder/vendor_rsp.rs
1. fix issue#203 Add test cases for commit#7950d3d5b926b2e099422d01c6cbc3f166bb5bd1
2. fix bugs introduced in PR#211 cargo test may fail at test_case0_aead_register
=> spdmlib: add test cases for vendor defined message

spdmlib/src/common/algo.rs, spdmlib/src/lib.rs, spdmlib/src/message/error.rs, spdmlib/src/secret/mod.rs, spdmlib/src/secret/secret_callback.rs, test/spdm-emu/src/lib.rs, test/spdm-emu/src/secret_impl_sample.rs
Introduce secret crate which aims at providing APIs for doing measurement,
signing data and expanding key.
=> Secret: Introduce Secret Crate.

spdmlib/src/message/measurement.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/responder/context.rs, spdmlib/src/responder/measurement_rsp.rs, spdmlib/src/secret/mod.rs, test/spdm-emu/src/secret_impl_sample.rs, test/spdm-responder-emu/src/main.rs
removed hardcoded measurement block in measurement_rsp.rs
=> measurement_rsp: remove hardcoded measurement block

spdmlib/src/common/error.rs, spdmlib/src/lib.rs, spdmlib/src/message/error.rs, spdmlib/src/message/mod.rs, spdmlib/src/message/respond_if_ready.rs, spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/end_session_req.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/get_capabilities_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/get_version_req.rs, spdmlib/src/requester/handle_error_response_req.rs, spdmlib/src/requester/heartbeat_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/key_update_req.rs, spdmlib/src/requester/mod.rs, spdmlib/src/requester/negotiate_algorithms_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/requester/respond_if_ready_req.rs, spdmlib/src/requester/vendor_req.rs, spdmlib/src/responder/context.rs, spdmlib/src/responder/mod.rs, spdmlib/src/responder/respond_if_ready_rsp.rs, spdmlib/src/time/mod.rs, spdmlib/src/time/time_callbacks.rs
Detailed change:
1. implemented respond if ready command
2. introduced time crate, which provide sleep functionality
3. add spdm error respond handle arm for different requesters' commands
=> Implemented respond if ready command

spdmlib/src/common/error.rs, spdmlib/src/requester/vendor_req.rs
=> Fix: fix typo and add pub visible control to SpdmError

spdmlib/src/common/mod.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/responder/measurement_rsp.rs
=> content_changed: change the type of content_changed in runtime_info to u8

spdmlib/src/crypto/spdm_ring/cert_operation_impl.rs
In some cases, `cargo build` may failed.
Example:
feature `std` is not set and target_os is not uefi or none.
=> Fix build failed in some cases.

spdmlib/src/common/key_schedule.rs
=> handshake_secret: Fix Handshake-Secret calculation

readme.md
=> readme: update readme

spdmlib/etc/config.json, spdmlib/src/common/algo.rs, spdmlib/src/common/spdm_codec.rs, test/spdm-emu/src/secret_impl_sample.rs
1. add new raw measurement type
2. enlarge max_measurement_val_len and max_measurement_block_count
to unblock testing with spdm_emu
=> get_measurement: add new raw measurement type

spdmlib/Cargo.toml, spdmlib/src/common/mod.rs
=> SpdmDeviceIo: add as_any interface for downcasting

spdmlib/src/message/vendor.rs, spdmlib/src/responder/vendor_rsp.rs
=> vendor_defined: provide interface to register VENDER_DEFINED handler.

fuzz-target/fuzzlib/src/fake_device_io.rs, spdmlib/src/common/mod.rs, spdmlib/src/common/session.rs, spdmlib/src/crypto/spdm_ring/aead_impl.rs, spdmlib/src/crypto/spdm_ring/cert_operation_impl.rs, spdmlib/src/crypto/spdm_ring/rand_impl.rs, spdmlib/src/message/vendor.rs, spdmlib/src/requester/end_session_req.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/handle_error_response_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/key_update_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/responder/context.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs
=> requester: remove unchecked unwrap()

spdmlib/src/crypto/mod.rs, spdmlib/src/crypto/spdm_ring/asym_verify_impl.rs
=> Fix  Tests bug

doc/mirai.md
=> DOC: introduce MIRAI for static analysis.

.github/workflows/main.yml, sh_script/fuzz_run.sh
=> CI/CD: Enable FuzzTest builds.

fuzz-target/fuzzlib/src/lib.rs, fuzz-target/fuzzlib/src/time.rs, fuzz-target/requester/version_req/src/main.rs, spdmlib/src/message/capability.rs, spdmlib/src/message/version.rs, spdmlib/src/requester/handle_error_response_req.rs
=> Fix some bugs

spdmlib/src/common/session.rs
Fixed #273
Signed-off-by: xiaoyuxlu <xiaoyu1.lu@intel.com>
=> Fix HASH(transcirpt) as HMAC input for Finish REQ/RSP

fuzz-target/pass_context/src/pass_requester.rs, fuzz-target/random_requester/src/main.rs, fuzz-target/requester/certificate_req/src/main.rs, fuzz-target/requester/digest_req/src/main.rs, spdmlib/src/requester/context.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs, spdmlib/tests/test_client_server.rs, test/spdm-requester-emu/src/main.rs
Fixed #282
Signed-off-by: xiaoyuxlu <xiaoyu1.lu@intel.com>
=> Add GET_DIGEST/GET_CERTIFICATE request in a session

spdmlib/src/requester/get_certificate_req.rs
=> get_certificate_req: add support for send_receive_spdm_certificate_partial in session

spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/end_session_req.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/get_capabilities_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/get_version_req.rs, spdmlib/src/requester/handle_error_response_req.rs, spdmlib/src/requester/heartbeat_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/key_update_req.rs, spdmlib/src/requester/negotiate_algorithms_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/requester/vendor_req.rs
=> add spdm_handle_error_response_main not in session support.

spdmlib/src/crypto/spdm_ring/hkdf_impl.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/key_update_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/responder/key_update_rsp.rs
1. add sanity check for hkdf_expand.
2. fix tests problems.
=> Add sanity check for hkdf_expand. Fix #292

spdmlib/tests/common/crypto_callbacks.rs, spdmlib_crypto_mbedtls/tests/common/crypto_callbacks.rs, spdmlib_crypto_mbedtls/tests/common/mod.rs, spdmlib_crypto_mbedtls/tests/common/utils.rs, test/spdm-emu/src/crypto_callback.rs
Cleanup functions and support for multiple RSA and ECDSA algorithms
=> clean sign_rsa_algo and sign_ecdsa_algo, Fix #296

spdmlib_crypto_mbedtls/Cargo.toml, spdmlib_crypto_mbedtls/readme.md, spdmlib_crypto_mbedtls/src/lib.rs, spdmlib_crypto_mbedtls/src/platform_support.rs
1. update build doc
2. add missing dependencies
=> Fix spdmlib_crypto_mbedtls build problem.

spdmlib_crypto_mbedtls/src/asym_verify_impl.c, spdmlib_crypto_mbedtls/src/asym_verify_impl.rs, spdmlib_crypto_mbedtls/src/ffi.rs, spdmlib_crypto_mbedtls/tests/common/crypto_callbacks.rs, spdmlib_crypto_mbedtls/tests/test_with_mbedtls.rs
Signed-off-by: xiaoyuxlu <xiaoyu1.lu@intel.com>
=> Add mbedtls RSA support

.github/workflows/coverage.yml
1. create coverage data
2. upload coverage data to codecov
=> CI/CD: add coverage.yml

spdmlib/src/crypto/crypto_tests.rs, spdmlib/src/crypto/mod.rs
=> Tests: add AEAD tests, Fixed #305

spdmlib/src/common/session.rs
Signed-off-by: Yang Longlong <longlong.yang@intel.com>
=> session: add functions to get/set application secret sequence number.

.github/workflows/coverage.yml, .github/workflows/main.yml, readme.md
It is now a standard cargo feature.
=> Switch to -Z build-std

.github/workflows/main.yml, fuzz-target/requester/key_exchange_req/src/main.rs, fuzz-target/requester/measurement_req/src/main.rs, sh_script/fuzz_run.sh, spdmlib/src/requester/key_exchange_req.rs
=> CI/CD: install AFL and cargo-fuzz for fuzzing test.

spdmlib/build.rs, spdmlib/src/common/mod.rs, spdmlib/src/common/session.rs, spdmlib/src/common/spdm_codec.rs, spdmlib/src/crypto/spdm_ring/aead_impl.rs, spdmlib/src/crypto/spdm_ring/hkdf_impl.rs, spdmlib/src/protocol/algo.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/responder/certificate_rsp.rs, spdmlib/src/responder/digest_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/measurement_rsp.rs, spdmlib_crypto_mbedtls/src/asym_verify_impl.c, spdmlib_crypto_mbedtls/src/asym_verify_impl.rs, spdmlib_crypto_mbedtls/src/lib.rs
=> Fix clippy issues.

sh_script/build.sh
1. Run check only ./sh_script/build.sh -c
2. Build rust-spdm ./sh_script/build.sh
3. Build and run tests ./sh_script/build.sh -r
Close #342
=> Add build script sh_script/build.sh

spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/responder/measurement_rsp.rs
=> Use clone instead of to_owned to avoid use of alloc

spdmlib/Cargo.toml, spdmlib/src/common/mod.rs, spdmlib/src/common/session.rs, spdmlib/src/crypto/crypto_callbacks.rs, spdmlib/src/crypto/mod.rs, spdmlib/src/crypto/spdm_ring/hash_impl.rs, spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/negotiate_algorithms_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/responder/algorithm_rsp.rs, spdmlib/src/responder/certificate_rsp.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/digest_rsp.rs, spdmlib/src/responder/finish_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/measurement_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs, spdmlib/src/responder/psk_finish_rsp.rs, test/spdm-emu/Cargo.toml
Fix #337 
Add the missing hash-update feature.
Rename feature from hash-update to hash-transcript-data
=> Rename feature "hash-update" to "hashed-transcript-data"

spdmlib/src/common/opaque.rs, spdmlib/src/message/algorithm.rs, spdmlib/src/protocol/algo.rs, spdmlib/src/requester/negotiate_algorithms_req.rs
=> Check requester algorithm response message,  Fix #331

spdmlib/src/responder/psk_finish_rsp.rs
=> Return true/false instead of unwrap for generate_data_secret

.github/workflows/coverage.yml, .github/workflows/fuzz.yml, .github/workflows/main.yml, sh_script/build.sh
=> CI/CD: Add hashed-transcript-data test configuration.

.github/workflows/fuzz.yml, .github/workflows/main.yml, sh_script/build.sh
=> Add hashed-transcript-cross check.

spdmlib/src/responder/certificate_rsp.rs, spdmlib/src/responder/digest_rsp.rs, spdmlib/src/responder/finish_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs
fix #356
Signed-off-by: Yang Longlong <longlong.yang@intel.com>
=> fix emu requester <-> responder test failure.

test/spdm-requester-emu/src/main.rs
fix #355
Signed-off-by: Yang Longlong <longlong.yang@intel.com>
=> add panicing when error occur during requester-emu running.

spdmlib/src/requester/get_measurements_req.rs
=> reset message_m after verify_measurement_signature.

fuzz-target/requester/certificate_req/src/main.rs, fuzz-target/requester/challenge_req/src/main.rs, fuzz-target/requester/digest_req/src/main.rs, fuzz-target/requester/key_exchange_req/src/main.rs, fuzz-target/requester/measurement_req/src/main.rs, fuzz-target/responder/certificate_rsp/src/main.rs, fuzz-target/responder/challenge_rsp/src/main.rs, fuzz-target/responder/digest_rsp/src/main.rs, fuzz-target/responder/measurement_rsp/src/main.rs, spdmlib/src/common/mod.rs, spdmlib/src/common/session.rs, spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/negotiate_algorithms_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/responder/algorithm_rsp.rs, spdmlib/src/responder/certificate_rsp.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/digest_rsp.rs, spdmlib/src/responder/finish_rsp.rs, spdmlib/src/responder/measurement_rsp.rs, spdmlib/src/responder/psk_finish_rsp.rs
=> rename message to digest when hash_update is enabled.

sh_script/build.sh
=> CI/CD: Add tests with spdm-emu requester and responder.

spdmlib/src/responder/context.rs, spdmlib/src/responder/psk_finish_rsp.rs
=> Remove or mark safe unwrap in psk_finish_rsp.rs

fuzz-target/fuzzlib/src/fake_device_io.rs, spdmlib/src/responder/app_message_handler.rs, spdmlib/src/responder/context.rs, spdmlib/src/responder/mod.rs, spdmlib/src/testlib.rs, spdmlib/tests/common/fake_device_io.rs, spdmlib/tests/common/testlib.rs, test/spdm-responder-emu/src/main.rs
fix https://github.com/jyao1/rust-spdm/issues/393
=> Support APP Message use case.

spdmlib/src/common/mod.rs, spdmlib/src/common/session.rs
fix https://github.com/jyao1/rust-spdm/issues/392
=> add return session status under SpdmContext support.

spdmlib/build.rs, spdmlib/etc/config.json, spdmlib/src/message/certificate.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/responder/certificate_rsp.rs
=> Remove max_cert_portion_len config

spdmlib/src/common/mod.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs
=> remove hardcoding of session id generation.

spdmlib/build.rs, spdmlib/etc/config.json
=> remove max_measurement_val_len from config.

spdmlib/build.rs, spdmlib/etc/config.json, spdmlib/src/message/vendor.rs, spdmlib/src/requester/vendor_req.rs, spdmlib/src/responder/vendor_rsp.rs
=> Remove max_vendor_defined_payload_size config

spdmlib/src/common/mod.rs, spdmlib/src/crypto/crypto_callbacks.rs, spdmlib/src/crypto/mod.rs, spdmlib/src/crypto/spdm_ring/hash_impl.rs, spdmlib/src/error.rs, spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/negotiate_algorithms_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/responder/algorithm_rsp.rs, spdmlib/src/responder/certificate_rsp.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/digest_rsp.rs, spdmlib/src/responder/finish_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/measurement_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs, spdmlib/src/responder/psk_finish_rsp.rs, test/spdm-emu/src/crypto_callback.rs, test/spdm-emu/src/spdm_emu.rs
=> remove unwrap in requester and common related code.

spdmlib/src/protocol/algo.rs
=> Remove should_panic in unit tests and update implementation.

spdmlib/src/crypto/spdm_ring/cert_operation_impl.rs
Ref #320 
1. invalid signature
2. invalid intermediate cert
=> Tests: Add tests for invalid certificate.

spdmlib/Cargo.toml, spdmlib/src/message/algorithm.rs, spdmlib/src/message/algorithm_test.rs, spdmlib/src/message/capability.rs, spdmlib/src/message/capability_test.rs, spdmlib/src/message/digest.rs, spdmlib/src/message/digest_test.rs, spdmlib/src/message/version.rs, spdmlib/src/message/version_test.rs
=> add corner tests

spdmlib/src/message/certificate.rs, spdmlib/src/message/certificate_test.rs, spdmlib/src/message/challenge.rs, spdmlib/src/message/challenge_test.rs, spdmlib/src/message/measurement.rs, spdmlib/src/message/measurement_test.rs
1. measurement
2. certificate
3. challenge
REF: #320
=> add more tests

codec/src/codec.rs, fuzz-target/fuzzlib/src/fake_device_io.rs, fuzz-target/fuzzlib/src/fuzz_aead_impl.rs, fuzz-target/fuzzlib/src/lib.rs, fuzz-target/pass_context/src/pass_requester.rs, fuzz-target/random_requester/src/main.rs, fuzz-target/requester/algorithm_req/src/main.rs, fuzz-target/requester/capability_req/src/main.rs, spdmlib/src/common/mod.rs, spdmlib/src/common/session.rs, spdmlib/src/common/spdm_codec.rs, spdmlib/src/crypto/spdm_ring/aead_impl.rs, spdmlib/src/crypto/spdm_ring/asym_verify_impl.rs, spdmlib/src/crypto/spdm_ring/cert_operation_impl.rs, spdmlib/src/message/digest_test.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/psk_finish_rsp.rs, spdmlib/tests/common/testlib.rs, test/spdm-emu/src/spdm_emu.rs
=> Code cleanup.

spdmlib/src/requester/vendor_req.rs, spdmlib/src/responder/context.rs, spdmlib/src/responder/vendor_rsp.rs
=> add outside of session support in vendor defined request/response.

pcidoe_transport/src/header.rs
=> fix DOE header length check.

.github/workflows/coverage.yml, .github/workflows/main.yml, readme.md, spdmlib_crypto_mbedtls/build.rs, spdmlib_crypto_mbedtls/readme.md, spdmlib_crypto_mbedtls/src/lib.rs
Fix: https://github.com/jyao1/rust-spdm/issues/439
=> change x86_64-unknown-uefi to none

spdmlib/src/common/mod.rs, spdmlib/src/common/session.rs, spdmlib/src/requester/context.rs, spdmlib/src/requester/key_exchange_req.rs
=> bugfix: fix the same next_half_session_id in get_next_half_session_id and start_session failure.

spdmlib/src/common/session.rs, spdmlib/src/responder/finish_rsp.rs, spdmlib/src/responder/psk_finish_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/437
=> add DHE/PSK mode switch detection

spdmlib/src/protocol/algo.rs
Fix: https://github.com/jyao1/rust-spdm/issues/457
=> remove FFDHE from prioritize table since they are unsupported.

fuzz-target/fuzzlib/src/requesterlib.rs, fuzz-target/fuzzlib/src/responderlib.rs, spdmlib/tests/common/mod.rs, spdmlib/tests/common/utils.rs, spdmlib_crypto_mbedtls/tests/common/mod.rs, spdmlib_crypto_mbedtls/tests/common/utils.rs, test/spdm-emu/src/spdm_emu.rs, test/spdm-requester-emu/src/main.rs, test/spdm-responder-emu/src/main.rs
Fix https://github.com/jyao1/rust-spdm/issues/458
=> remove USE_ECDHE, since we only support ECDHE.

spdmlib/src/protocol/algo.rs
Fix: https://github.com/jyao1/rust-spdm/issues/459
Sigend-off-by: Jiewen Yao <jiewen.yao@intel.com>
=> zero the algorithm if it is not in priority table.

spdmlib/src/message/heartbeat_test.rs, spdmlib/src/requester/key_exchange_req.rs
Fix https://github.com/jyao1/rust-spdm/issues/469
=> resolve warning in cargo test

spdmlib/src/protocol/algo.rs
Fix: https://github.com/jyao1/rust-spdm/issues/462
=> use same prioritize table for asym and reqasym.

spdmlib/src/responder/algorithm_rsp.rs, spdmlib/src/responder/capability_rsp.rs, spdmlib/src/responder/certificate_rsp.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/context.rs, spdmlib/src/responder/digest_rsp.rs, spdmlib/src/responder/end_session_rsp.rs, spdmlib/src/responder/finish_rsp.rs, spdmlib/src/responder/heartbeat_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/key_update_rsp.rs, spdmlib/src/responder/measurement_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs, spdmlib/src/responder/psk_finish_rsp.rs, spdmlib/src/responder/respond_if_ready_rsp.rs, spdmlib/src/responder/version_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/449
=> Add responder version check

spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs
Fix: https://github.com/jyao1/rust-spdm/issues/441
=> support send get cert in session.

spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs, spdmlib/src/responder/certificate_rsp.rs, spdmlib/src/responder/digest_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/492
=> Skip m1m2 for digest/cert no in session.

spdmlib/src/requester/heartbeat_req.rs, spdmlib/src/requester/key_update_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/responder/context.rs
Fix: https://github.com/jyao1/rust-spdm/issues/440
=> Add session handshake state check

spdmlib/src/responder/context.rs, spdmlib/src/responder/end_session_rsp.rs, spdmlib/src/responder/finish_rsp.rs, spdmlib/src/responder/heartbeat_rsp.rs, spdmlib/src/responder/key_update_rsp.rs, spdmlib/src/responder/psk_finish_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/476
=> Use consistent way for write_spdm_key_update_response

spdmlib/build.rs, spdmlib/etc/config.json, spdmlib/src/message/algorithm.rs, spdmlib/src/message/mod.rs, spdmlib/src/responder/algorithm_rsp.rs
Fix: https://github.com/jyao1/rust-spdm/issues/487
=> remove algo_config since it is not configurable

fuzz-target/responder/psk_finish_rsp/src/main.rs, spdmlib/src/common/opaque.rs, spdmlib/src/crypto/spdm_ring/dhe_impl.rs, spdmlib/src/message/algorithm.rs, spdmlib/src/message/certificate.rs, spdmlib/src/message/challenge.rs, spdmlib/src/message/digest.rs, spdmlib/src/message/digest_test.rs, spdmlib/src/message/end_session.rs, spdmlib/src/message/error.rs, spdmlib/src/message/finish.rs, spdmlib/src/message/heartbeat.rs, spdmlib/src/message/key_exchange.rs, spdmlib/src/message/measurement.rs, spdmlib/src/message/mod.rs, spdmlib/src/message/psk_exchange.rs, spdmlib/src/message/psk_finish.rs, spdmlib/src/message/version.rs, spdmlib/src/protocol/algo.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/responder/algorithm_rsp.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs, spdmlib/tests/test_library.rs, spdmlib_crypto_mbedtls/src/asym_verify_impl.rs, spdmlib_crypto_mbedtls/src/dhe_impl.rs, test/spdm-emu/src/secret_impl_sample.rs
Fix https://github.com/jyao1/rust-spdm/issues/510
=> remove unsupported algorithms

spdmlib/src/message/algorithm.rs, spdmlib/src/message/algorithm_test.rs, spdmlib/src/message/capability.rs, spdmlib/src/message/certificate.rs, spdmlib/src/message/mod.rs, spdmlib/src/protocol/algo.rs, spdmlib/src/requester/negotiate_algorithms_req.rs, spdmlib/src/responder/algorithm_rsp.rs, spdmlib/src/responder/capability_rsp.rs
Fix: https://github.com/jyao1/rust-spdm/issues/478
Fix: https://github.com/jyao1/rust-spdm/issues/448
=> Add version check for algorithm and capability.

spdmlib/src/protocol/algo.rs
Fix https://github.com/jyao1/rust-spdm/issues/517
=> remove SpdmExtAlgStruct since we dont support ext_algo

spdmlib/build.rs, spdmlib/etc/config.json, spdmlib/src/common/opaque.rs, spdmlib/src/message/challenge.rs, spdmlib/src/message/key_exchange.rs, spdmlib/src/message/measurement.rs, spdmlib/src/message/mod.rs, spdmlib/src/message/mod_test.common.inc.rs, spdmlib/src/message/psk_exchange.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/measurement_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs, spdmlib/tests/test_library.rs
Fix https://github.com/jyao1/rust-spdm/issues/488
=> remove max_opaque_size

fuzz-target/fuzzlib/src/secret.rs, spdmlib/build.rs, spdmlib/etc/config.json, spdmlib/src/common/spdm_codec.rs, spdmlib/src/message/measurement.rs, spdmlib/src/message/mod.rs, spdmlib/src/protocol/algo.rs, spdmlib/tests/test_library.rs, test/spdm-emu/src/secret_impl_sample.rs
Fix https://github.com/jyao1/rust-spdm/issues/521
=> Add MAX_SPDM_MEASUREMENT_RECORD_SIZE to config

spdmlib/src/common/spdm_codec.rs
Fix https://github.com/jyao1/rust-spdm/issues/454
=> add more check for measurement record.

spdmlib/src/common/opaque.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/509
=> clean up FMT1 usage.

spdmlib/src/crypto/spdm_ring/cert_operation_impl.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib_crypto_mbedtls/src/cert_operation_impl.rs
Fix https://github.com/jyao1/rust-spdm/issues/481
=> Add invalid cert length check

spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/end_session_req.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/get_capabilities_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/get_version_req.rs, spdmlib/src/requester/handle_error_response_req.rs, spdmlib/src/requester/heartbeat_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/key_update_req.rs, spdmlib/src/requester/negotiate_algorithms_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/requester/vendor_req.rs
fix https://github.com/jyao1/rust-spdm/issues/533
=> remove requester error handling to resend message.

fuzz-target/fuzzlib/src/requesterlib.rs, fuzz-target/fuzzlib/src/responderlib.rs, fuzz-target/requester/certificate_req/src/main.rs, spdmlib/src/common/mod.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/testlib.rs, spdmlib/tests/common/testlib.rs, spdmlib/tests/common/utils.rs, spdmlib_crypto_mbedtls/tests/common/utils.rs, test/spdm-requester-emu/src/main.rs, test/spdm-responder-emu/src/main.rs
Fix https://github.com/jyao1/rust-spdm/issues/527
Fix https://github.com/jyao1/rust-spdm/issues/512
=> add root_cert_data provision

fuzz-target/fuzzlib/src/requesterlib.rs, fuzz-target/fuzzlib/src/responderlib.rs, spdmlib/src/common/mod.rs, spdmlib/src/requester/get_version_req.rs, spdmlib/src/testlib.rs, spdmlib/tests/common/testlib.rs, spdmlib/tests/common/utils.rs, spdmlib_crypto_mbedtls/tests/common/utils.rs, test/spdm-requester-emu/src/main.rs, test/spdm-responder-emu/src/main.rs
Fix https://github.com/jyao1/rust-spdm/issues/529
=> remove default_version, since we have that in SpdmConfigInfo

readme.md
=> doc: add run emulator without hashed-transcript-data feature.

pcidoe_transport/src/header.rs, spdmlib/src/testlib.rs, spdmlib/tests/common/testlib.rs
Fix https://github.com/jyao1/rust-spdm/issues/546
=> add DOE length cast.

spdmlib/src/message/capability.rs, spdmlib/src/message/mod.rs, spdmlib/src/protocol/capability.rs, spdmlib/src/responder/capability_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/452
Fix https://github.com/jyao1/rust-spdm/issues/450
=> Add capability check

spdmlib/build.rs, spdmlib/src/requester/get_certificate_req.rs
Fix https://github.com/jyao1/rust-spdm/issues/551
=> Add check for cert remainder_length

spdmlib/src/message/challenge.rs, spdmlib/src/message/key_exchange.rs, spdmlib/src/message/key_exchange_test.rs, spdmlib/src/message/mod.rs, spdmlib/src/message/psk_exchange.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/psk_exchange_req.rs
Fix https://github.com/jyao1/rust-spdm/issues/547
=> Add measurement_summary_hash_type check.

spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/responder/certificate_rsp.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/measurement_rsp.rs
fix typo.
slot_id must less than SPDM_MAX_SLOT_NUMBER.
Fix: https://github.com/jyao1/rust-spdm/issues/497
=> add slot_id check

spdmlib/src/common/opaque.rs, spdmlib/src/message/algorithm.rs, spdmlib/src/protocol/algo.rs
Fix: https://github.com/jyao1/rust-spdm/issues/460
=> Add algorithm check.

spdmlib/src/common/spdm_codec.rs, spdmlib/src/message/algorithm.rs, spdmlib/src/message/measurement.rs, spdmlib/src/message/mod.rs, spdmlib/src/responder/algorithm_rsp.rs, spdmlib/tests/test_library.rs, test/spdm-emu/src/secret_impl_sample.rs
Fix https://github.com/jyao1/rust-spdm/issues/556
=> add check for SpdmMeasurementRecordStructure and SpdmDmtfMeasurementStructure

spdmlib/build.rs, spdmlib/etc/config.json, spdmlib/src/common/opaque.rs, spdmlib/src/message/vendor.rs, spdmlib/src/requester/vendor_req.rs, tdisp/src/common.rs
Fix https://github.com/jyao1/rust-spdm/issues/525
=> clean up MAX_VENDOR_ID_LENGTH

spdmlib/src/responder/context.rs
=> Tests: Fix test failure.

spdmlib/src/common/mod.rs, spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/get_capabilities_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/negotiate_algorithms_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/responder/algorithm_rsp.rs, spdmlib/src/responder/capability_rsp.rs, spdmlib/src/responder/certificate_rsp.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/context.rs, spdmlib/src/responder/digest_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/measurement_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/513
=> check SpdmConnectionState for unexpected request message

spdmlib/src/responder/context.rs
REF: #560
GET_VERSION not only resets the runtime info but also other context info. Test also has this problem. This patch fixes the test issue.
=> Tests: Fix test issue.

spdmlib/src/requester/get_capabilities_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/responder/capability_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs, spdmlib/src/responder/vendor_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/477
=> Add more version check

spdmlib/src/requester/context.rs, spdmlib/src/responder/context.rs
Fix https://github.com/jyao1/rust-spdm/issues/482
=> Add peer receiver buffer size check.

spdmlib/Cargo.toml, spdmlib/src/common/mod.rs, spdmlib/src/common/session.rs, spdmlib/src/crypto/crypto_callbacks.rs, spdmlib/src/crypto/crypto_tests.rs, spdmlib/src/crypto/mod.rs, spdmlib/src/crypto/spdm_ring/hash_impl.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/responder/key_exchange_rsp.rs
=> Remove ring dependency for crypto interface.

spdmlib/src/crypto/spdm_ring/asym_verify_impl.rs
=> crypto review action: distinguish the RSA and default branch

spdmlib/src/crypto/spdm_ring/aead_impl.rs
=> crypto review action: Remove the resolve of algorithm and do it in make_key

codec/src/macros.rs, mctp_transport/src/header.rs, pcidoe_transport/src/header.rs, spdmlib/src/common/mod.rs, spdmlib/src/common/session.rs, spdmlib/src/message/error.rs, spdmlib/src/message/key_update.rs, spdmlib/src/message/key_update_test.rs, spdmlib/src/message/measurement.rs, spdmlib/src/message/mod.rs, spdmlib/src/protocol/algo.rs, spdmlib/src/protocol/version.rs, spdmlib/src/testlib.rs, spdmlib/tests/common/testlib.rs
Fix https://github.com/jyao1/rust-spdm/issues/411
Fix https://github.com/jyao1/rust-spdm/issues/600
=> remove Unknown(0) as default in enum_builder

pcidoe_transport/src/header.rs, spdmlib/src/testlib.rs, spdmlib/tests/common/testlib.rs
Fix https://github.com/jyao1/rust-spdm/issues/406
=> Add more DOE header length check.

fuzz-target/fuzzlib/src/fuzz_aead_impl.rs, spdmlib/src/crypto/bytes_mut_scrubbed.rs, spdmlib/src/crypto/mod.rs, spdmlib/src/crypto/spdm_ring/aead_impl.rs, spdmlib/src/crypto/spdm_ring/dhe_impl.rs, spdmlib/src/protocol/algo.rs, spdmlib/src/responder/key_exchange_rsp.rs
=> crypto review action: in_out is a BytesMut instance should be scrubbed before returning

spdmlib/src/crypto/crypto_callbacks.rs, spdmlib/src/crypto/mod.rs, spdmlib/src/crypto/spdm_ring/hash_impl.rs, spdmlib_crypto_mbedtls/Cargo.toml, spdmlib_crypto_mbedtls/src/ffi_ext.rs, spdmlib_crypto_mbedtls/src/hash_impl.rs, spdmlib_crypto_mbedtls/src/lib.rs, spdmlib_crypto_mbedtls/tests/test_hash_update.rs
=> crypto/mbedtls: Add hashed-transcript-data support

fuzz-target/requester/certificate_req/src/main.rs, fuzz-target/requester/challenge_req/src/main.rs, fuzz-target/requester/digest_req/src/main.rs, fuzz-target/requester/key_exchange_req/src/main.rs, fuzz-target/requester/measurement_req/src/main.rs, fuzz-target/responder/certificate_rsp/src/main.rs, fuzz-target/responder/challenge_rsp/src/main.rs, fuzz-target/responder/digest_rsp/src/main.rs, fuzz-target/responder/measurement_rsp/src/main.rs, spdmlib/src/common/mod.rs, spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/get_capabilities_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs, spdmlib/src/requester/get_version_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/negotiate_algorithms_req.rs, spdmlib/src/responder/algorithm_rsp.rs, spdmlib/src/responder/capability_rsp.rs, spdmlib/src/responder/certificate_rsp.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/context.rs, spdmlib/src/responder/digest_rsp.rs, spdmlib/src/responder/version_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/580
=> remove external initialization for digest_context_m1m2

spdmlib/src/common/mod.rs, spdmlib/src/requester/challenge_req.rs, spdmlib/src/responder/challenge_rsp.rs
Ref: https://github.com/jyao1/rust-spdm/issues/580
=> Add reset_message_b/c.

spdmlib/src/common/mod.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/responder/measurement_rsp.rs
Ref: https://github.com/jyao1/rust-spdm/issues/580
=> add append_message_m

spdmlib/src/common/mod.rs, spdmlib/src/common/session.rs, spdmlib/src/crypto/mod.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs
Ref https://github.com/jyao1/rust-spdm/issues/580
=> Add append_message_k

spdmlib/src/common/mod.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/responder/finish_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs, spdmlib/src/responder/psk_finish_rsp.rs
Ref https://github.com/jyao1/rust-spdm/issues/580
=> Add append_message_f.

spdmlib/src/message/key_exchange.rs, spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/get_capabilities_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/responder/capability_rsp.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/measurement_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/612
=> fix SPDM 1.2 version comparison

spdmlib/src/common/mod.rs, spdmlib/src/common/session.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/requester/psk_exchange_req.rs, spdmlib/src/requester/psk_finish_req.rs, spdmlib/src/responder/finish_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs, spdmlib/src/responder/psk_finish_rsp.rs
Fix: https://github.com/jyao1/rust-spdm/issues/616
=> hide #[cfg(not(feature = "hashed-transcript-data"))] in session message

spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/measurement_rsp.rs
Fix: https://github.com/jyao1/rust-spdm/issues/616
=> remove feature = "hashed-transcript-data" in challenge.

spdmlib/src/common/mod.rs, spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/measurement_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/579
=> Add ManagedBuffer12Sign to reduce size in hash mode.

doc/fuzzing.md
Add cargo fuzz (libfuzzer) support
Fix #582
=> docs: update fuzzing.md.

.github/workflows/coverage.yml, .github/workflows/deny.yml, .github/workflows/format.yml, .gitmodules, Cargo.toml, external/patches/ring/0001-Support-x86_64-unknown-none-target.patch, external/patches/webpki/0001-Add-support-for-verifying-certificate-chain-with-EKU.patch, fuzz-target/fuzzlib/Cargo.toml, sh_script/build.sh, sh_script/pre-build.sh, spdmlib/Cargo.toml, spdmlib_crypto_mbedtls/Cargo.toml, test/spdm-emu/Cargo.toml
Fix #607.
This approach leverages cargo's overriding dependencies feature. For more information:  https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html
=> Use ring/webpki as submodule and apply patches on them

fuzz-target/responder/finish_rsp/src/main.rs, spdmlib/src/common/mod.rs, spdmlib/src/message/finish.rs, spdmlib/src/message/key_exchange.rs, spdmlib/src/requester/finish_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/responder/context.rs, spdmlib/src/responder/finish_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/531
=> add HANDSHAKE_IN_THE_CLEAR_CAP.

spdmlib/src/common/key_schedule.rs, spdmlib/src/crypto/crypto_callbacks.rs, spdmlib/src/crypto/mod.rs, spdmlib/src/crypto/spdm_ring/hkdf_impl.rs, spdmlib_crypto_mbedtls/src/hkdf_impl.rs
Fix https://github.com/jyao1/rust-spdm/issues/625
=> define hkdf-extract to make flow clear

spdmlib/src/responder/algorithm_rsp.rs
Add write_spdm_error before return.
Fix #645
=> Add write_spdm_error

spdmlib/src/responder/psk_exchange_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/635
=> fix psk_context_size

fuzz-target/requester/algorithm_req/src/main.rs, fuzz-target/requester/capability_req/src/main.rs, fuzz-target/requester/certificate_req/src/main.rs, fuzz-target/requester/challenge_req/src/main.rs, fuzz-target/requester/digest_req/src/main.rs, fuzz-target/requester/key_exchange_req/src/main.rs, fuzz-target/requester/measurement_req/src/main.rs, fuzz-target/requester/psk_exchange_req/src/main.rs, fuzz-target/responder/algorithm_rsp/src/main.rs, fuzz-target/responder/capability_rsp/src/main.rs, fuzz-target/responder/certificate_rsp/src/main.rs, fuzz-target/responder/challenge_rsp/src/main.rs, fuzz-target/responder/digest_rsp/src/main.rs, fuzz-target/responder/measurement_rsp/src/main.rs, fuzz-target/responder/pskexchange_rsp/src/main.rs
Add SpdmConnectionState provision for fuzz code to pass the check introduced by #571
=> Fuzz: add connection state provision

fuzz-target/fuzzlib/src/secret.rs, fuzz-target/requester/challenge_req/src/main.rs, fuzz-target/requester/key_exchange_req/src/main.rs, fuzz-target/requester/psk_exchange_req/src/main.rs, fuzz-target/responder/challenge_rsp/src/main.rs, fuzz-target/responder/keyexchange_rsp/src/main.rs, fuzz-target/responder/pskexchange_rsp/src/main.rs, spdmlib/src/requester/context.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/context.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/measurement_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs, spdmlib/src/secret/mod.rs, spdmlib/src/secret/secret_callback.rs, spdmlib/src/testlib.rs, test/spdm-emu/src/secret_impl_sample.rs
Fix https://github.com/jyao1/rust-spdm/issues/650
=> enable measurement_summary_hash calc.

spdmlib/src/crypto/spdm_ring/asym_verify_impl.rs
=> change the return type of ecc_signature_bin_to_der to report error

spdmlib/src/crypto/spdm_ring/asym_verify_impl.rs, spdmlib_crypto_mbedtls/src/asym_verify_impl.rs
=> need to check the sign_size base on algorithm.

spdmlib/src/crypto/spdm_ring/asym_verify_impl.rs, spdmlib_crypto_mbedtls/src/asym_verify_impl.rs
=> need more check on type conversion within ecc_signature_bin_to_der.

spdmlib/src/requester/finish_req.rs
=> Check session after handle_spdm_finish_response

spdmlib/src/crypto/spdm_ring/asym_verify_impl.rs, spdmlib_crypto_mbedtls/src/asym_verify_impl.rs
=> remove all magic number in asym_verify_impl.

spdmlib/src/requester/challenge_req.rs, spdmlib/src/requester/get_measurements_req.rs, spdmlib/src/requester/key_exchange_req.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/measurement_rsp.rs
Ref https://github.com/jyao1/rust-spdm/issues/613
=> return unsupported for 1.0/1.1 signing with hashed-transcript-data

spdmlib/src/requester/end_session_req.rs, spdmlib/src/requester/get_capabilities_req.rs, spdmlib/src/requester/get_certificate_req.rs, spdmlib/src/requester/get_digests_req.rs, spdmlib/src/requester/get_version_req.rs, spdmlib/src/requester/heartbeat_req.rs, spdmlib/src/requester/key_update_req.rs, spdmlib/src/requester/negotiate_algorithms_req.rs, spdmlib/src/responder/algorithm_rsp.rs, spdmlib/src/responder/capability_rsp.rs, spdmlib/src/responder/certificate_rsp.rs, spdmlib/src/responder/challenge_rsp.rs, spdmlib/src/responder/digest_rsp.rs, spdmlib/src/responder/end_session_rsp.rs, spdmlib/src/responder/finish_rsp.rs, spdmlib/src/responder/heartbeat_rsp.rs, spdmlib/src/responder/key_exchange_rsp.rs, spdmlib/src/responder/key_update_rsp.rs, spdmlib/src/responder/measurement_rsp.rs, spdmlib/src/responder/psk_exchange_rsp.rs, spdmlib/src/responder/psk_finish_rsp.rs, spdmlib/src/responder/vendor_rsp.rs, spdmlib/src/responder/version_rsp.rs
Fix https://github.com/jyao1/rust-spdm/issues/19
=> handle encode error

spdmlib/src/crypto/mod.rs, spdmlib/src/crypto/spdm_ring/asym_verify_impl.rs, spdmlib/src/crypto/x509v3.rs
=> verify the integrity of certicate chain before extract leaf certificate.

fuzz-target/fuzzlib/src/fake_aead_impl.rs, spdmlib/src/common/session.rs, spdmlib/src/crypto/crypto_callbacks.rs, spdmlib/src/crypto/crypto_tests.rs, spdmlib/src/crypto/mod.rs, spdmlib/src/crypto/spdm_ring/aead_impl.rs, spdmlib/src/requester/context.rs, spdmlib/src/requester/end_session_req.rs, spdmlib/src/requester/heartbeat_req.rs, spdmlib/src/responder/context.rs, spdmlib/src/responder/end_session_rsp.rs, spdmlib/src/responder/heartbeat_rsp.rs, spdmlib_crypto_mbedtls/src/aead_impl.rs
=> use composite types for key and iv.

.github/workflows/coverage.yml, doc/coverage.md, sh_script/build.sh, sh_script/fuzz_run.sh
1. Fix alf fail.
2. Fix deprecated warnings for coverage.
3. Update coverage flow. Make it clearer.
=> [CI/CD] update coverage.yml

spdmlib/src/responder/encap_rsp.rs
Responder should encode an error message into the response buffer and send it through the secure session to requster when handling the error of encapsulated request.
=> spdmlib: fix the error handling in `encap_rsp`

spdmlib/src/responder/finish_rsp.rs
When cargo feature `mut-auth` is enabled, the `mut_auth_requested` will be set to a non-zero value. Responder should check the `finish_request_attributes` in the finish request and return error message if `mut_auth_requested` is set.
=> spdmlib: return error if `SIGNATURE_INCLUDED` is not set

spdmlib/src/message/encapsulated.rs, spdmlib/src/message/encapsulated_test.rs, spdmlib/src/message/key_exchange_test.rs, spdmlib/src/requester/encap_req.rs, test/spdmlib-test/Cargo.toml, test/spdmlib-test/src/common/crypto_callback.rs, test/spdmlib-test/src/common/util.rs, test/spdmlib-test/src/requester_tests/context.rs, test/spdmlib-test/src/requester_tests/encap_certificate.rs, test/spdmlib-test/src/requester_tests/encap_digest.rs, test/spdmlib-test/src/requester_tests/encap_error.rs, test/spdmlib-test/src/requester_tests/encap_req.rs, test/spdmlib-test/src/requester_tests/key_exchange_req.rs, test/spdmlib-test/src/requester_tests/mod.rs, test/spdmlib-test/src/responder_tests/capability_rsp.rs, test/spdmlib-test/src/responder_tests/encap_get_certificate.rs, test/spdmlib-test/src/responder_tests/encap_get_digest.rs, test/spdmlib-test/src/responder_tests/encap_rsp.rs, test/spdmlib-test/src/responder_tests/mod.rs, test/spdmlib-test/src/test_client_server.rs
Fix https://github.com/jyao1/rust-spdm/issues/691
=> spdmlib: add unit test for encapsulated request/response 
